#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-ProcedureCall
version:      0.07
version_from: ProcedureCall.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
